# -*- coding: utf-8 -*-
"""백준 16953 (A->B)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S_fzEhG_aIFfnp8Uem0PQk1A_fSvQeZ8

정수 A를 B로 바꾸려고 한다. 가능한 연산은 다음과 같은 두 가지이다.

- 2를 곱한다.
- 1을 수의 가장 오른쪽에 추가한다. 
- A를 B로 바꾸는데 필요한 연산의 최솟값을 구해보자.

**중요 뽀인트!!**

- B를 줄여가면서 A랑 같은지 볼텐데,, B가 0이 되어버리면 무한루프에 빠진다..

    - 방법 1) 아래 코드처럼 elif문 안에 if문을 추가한다

    - 방법 2) if B == 0: 을 if문의 첫 조건으로 넣는다..
"""

A, B = map(int, input().split())

makable = True
count = 0
while (A != B):
    if B % 10 == 1:
        B = B // 10
        count += 1
    elif B % 2 == 0:
        if B == 0:
            makable = False
            break
        B = B // 2
        count += 1
    else :
        makable = False
        break

if makable:
    print(count + 1)
else:
    print(-1)