# -*- coding: utf-8 -*-
"""백준 9613 (GCD 합)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wG-B-BoLGlXtsSD0s-Tc2EzQvzTkNoed

**중요 포인트**

- 최대공약수 구하기
- 소팅 한 번해서 크기 크기순으로..
- 정수형 변수 sum에 계속 더하기
"""

#b가 더 크다고 가정
def make_GCD(a, b):
    while (a > 0):
        a, b = b % a, a
    return b

T = int(input())

for _ in range(T):
    #a[0] 은 갯수.. -> len(a) = a[0]..
    a = list(map(int, input().split()))
    N = a[0]
    nums = a[1:N+1]     #N개..
    nums.sort()         #정렬..
    sum = 0
    for i in range(N-1):
        for j in range(i+1,N):
            sum = sum + make_GCD(nums[i], nums[j])
    print(sum)

def make_GCD(a, b):
    while (a > 0):
        a, b = b % a, a
    return b

print(make_GCD(15,25))3