# -*- coding: utf-8 -*-
"""백준 2748 (피보나치 2)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14Jnq-ykgMu7TJrl96qOk3QIj8iqGKpKB
"""

#백준 2748
def fib(n):
    if n < 2 :
        return n
    else:
        fib_0 = 0
        fib_1 = 1
        for i in range(1,n):
            fib_0, fib_1 = fib_1, fib_0 + fib_1
        return fib_1

n = int(input())
print(fib(n))