# -*- coding: utf-8 -*-
"""백준 1010번 (다리놓기)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m0i2J3bmktZWu7cegtk0srAkcdSpk4Oh
"""

#백준 1010
#mCn을 math함수 안쓰고 반복문으로 구하기
T = int(input())

for i in range(T):
    N, M = map(int, input().split())
    initial_N, initial_M = 1, 1
    initial_M_N = 1

    for n in range(N):
        initial_N = initial_N * (n+1)

    for m in range(M):
        initial_M = initial_M * (m+1)

    for k in range(M-N):
        initial_M_N = initial_M_N * (k+1)
    
    s = initial_M / (initial_N * initial_M_N)
    print(int(s))