# -*- coding: utf-8 -*-
"""백준 20546 (기적의 매매법)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sEjRdfDxLrsd_v68tNklVGqS6mRbeAyE
"""

seed = int(input())
price = list(map(int,input().split()))

seed_JH = seed
num_stock_JH = 0
seed_SM = seed
num_stock_SM = 0

for i in range(14):
    if seed_JH >= price[i] :
        num_stock_JH += seed_JH // price[i]     #seed를 먼저바꾸면(아랫줄과 위치가 바뀌면)
        seed_JH = seed_JH % price[i]            #오류가 남..
    if seed_JH == 0:
        break

seed_JH = num_stock_JH * price[-1] + seed_JH

for i in range(2,14):
    if price[i] < price[i-1] and price[i-1] < price[i-2] and price[i-2] < price[i-3]:
        num_stock_SM += seed_SM // price[i]
        seed_SM = seed_SM % price[i]
        #매수

    elif price[i] > price[i-1] and price[i-1] > price[i-2] and price[i-2] > price[i-3]:
        seed_SM = num_stock_SM * price[i] + seed_SM
        num_stock_SM = 0
        #매도

seed_SM = num_stock_SM * price[-1] + seed_SM

if seed_JH > seed_SM :
    print('BNP')
elif seed_JH < seed_SM :
    print('TIMING')
else :
    print('SAMESAME')

5%2

