# -*- coding: utf-8 -*-
"""백준15894 (수학은 체육과목입니다)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ayfWSJW2hsiKCmyYmrtFt5t_8UMQT7UU
"""

#백준 15894

n = int(input())

print(4*n)