# -*- coding: utf-8 -*-
"""백준 1120 (문자열)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eqaqdJ_d4hHiJ2UaKSzI_SUpUx3Tq1Fq
"""

#차이를 출력하는거니까 옮겨가면서 차이를 보면 된다..

A, B = map(str, input().split())

differ = []
for i in range(len(B) - len(A) + 1):
    cnt = 0
    for j in range(len(A)):
        if (A[j] != B[i+j]):
            cnt = cnt+1
    differ.append(cnt)

print(min(differ))

def is_prime(n):
    if n == 1:
        return False
    if n == 2:
        return True
    for i in range(2, n):
        if n % i == 0:
            return False
    return True

dp = [False, False] + [True] * (N-1)

for i in range(2, N+1):
    if dp[i]:
        for j in range(2*i, N+1, i):
            dp[j] = False