# -*- coding: utf-8 -*-
"""백준 10828번(스택)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OjuEWjfASd1ro_oUML3Gs-DUKMfvOivz

함수로 하나 그냥 바로 하나 시간초과는 둘다 안뜸!
"""

#백준 10828

def push(x):
    seq.append(x)

def pop():
    if len(seq) == 0:
        print(-1)
    else:
        print(seq.pop())

def size():
    print(len(seq))

def empty():
    if seq:
        print(0)
    else:
        print(1)

def top():
    if seq:
        print(seq[-1])
    else:
        print(-1)

N = int(input())
seq = []

for i in range(N):
    m = input()
    m = m.split(" ")

    if m[0] == 'push':
        push(m[1])
        
    elif m[0] == 'pop':
        pop()

    elif m[0] == 'size':
        size()
        
    elif m[0] == 'empty':
        empty()
        
    elif m[0] == 'top':
        top()

#import sys

N = int(input())
seq = []
for i in range(N):
    m = input().split()
    #m = sys.stdin.readline().rstrip().split()
    # readline으로 받으면 끝의 개행문자까지 받아오므로 rstrip()으로 없에줘야함..

    if m[0] == 'push':
        seq.append(m[1])
    elif m[0] == 'pop':
        if seq:
            print(seq.pop())
        else:
            print(-1)
    elif m[0] == 'size':
        print(len(seq))
    elif m[0] == 'empty':
        if seq:
            print(0)
        else:
            print(1)
    elif m[0] == 'top':
        if seq:
            print(seq[-1])
        else:
            print(-1)

