# -*- coding: utf-8 -*-
"""백준 9020 (골드바흐의 추측)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11aErnEQ5vtjpl_9Ad0oXiJ2fAV5-27i2
"""

#백준 9020
def isPrime(num):
    for i in range(2, int(num**1/2)+1):
        if num % i == 0:
            return False
    return True

T = int(input())
for case in range(T):
    n = int(input())
    half = int(n / 2)
    for j in range(half):
        a = half - j
        b = half + j
        if (isPrime(a)) and (isPrime(b)):
            break
    print(a, b)