# -*- coding: utf-8 -*-
"""백준 9550(아이들은 사탕을 좋아해)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b7INrBw7VNCzP4iHIhSsMn-JW_hiIW4q
"""

#백준 9550

T = int(input())                #테스트 케이스 입력

for i in range(T):              #테스트 케이스에 대해서...
    kids = 0                    #몇명 올수 있는지 초기값 설정

    N, K = map(int, input().split())        # N 종류의 사탕, K개를 먹어야 만족

    a = [int(x) for x in input().split()]
    #람다함를 이용해서 한줄에 공백기준으로 입력받는 법... 리스트로...

    for j in range(N):
        kids += a[j] // K

    print(kids)

a = [int(x) for x in input().strip().split()]
print(a)

a = [int(x) for x in input().split()]
print(a)