# -*- coding: utf-8 -*-
"""백준 1024 (수열의 합)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FbXkgCgBzYWwsaxfC-hbkPtDe83Nq7II

**문제**

- N과 L이 주어진다
- 합이 N이면서, 길이가 적어도 L인 가장 짧은 연속된 음이 아닌 정수 리스트를 구하라

**풀이**

- a는 L개의 정수의 초항이다
- a부터 공차가 1인 등차수열의 합(L개)이 N일 때, a를 N과 L로 표현했다
- a가 음이 아닌 정수가 아니면 L을 하나 올려서 다시 찾는다
- 출력한다
"""

N, L = map(int, input().split())

found = False
while (L<101):
    #초항을 N, L으로 표현했다
    a = N/L - (L-1)/2
    #그게 음이 아니고 정수이면 찾은 것이고 break했다
    if (a >= 0) and (a // 1 == a):
        found = True
        break
    #찾지 못했으면 하나 더 긴 리스트로 판단해보아야 한다
    L += 1

#출력..
if found:
    for i in range(int(a), int(a)+L):
        print(i, end = " ")
else:
    print(-1)

"""
정수인가를 확인하는 방법
"""

print((1.1 // 1) == (1 // 1))

