# -*- coding: utf-8 -*-
"""백준 2355 (시그마)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z9hUBiGIcPZGQqrMyekwjTc0SfkwQO5Y
"""

#백준 2355

A, B = map(int, input().split())

if A > B :
    Big = A
    Small = B
else :
    Big = B
    Small = A

sigma = (Big - Small + 1) * (Big + Small) / 2

print(int(sigma))