# -*- coding: utf-8 -*-
"""백준 1620 (나는야 포켓몬 마스터 이다솜)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kK3Z9t1gvkyO2i5JmbQLoSUkru8x0OKN

딕셔너리에 저장해놓고 확인하는 법..

- 그냥 무지성으로 키에 정수를 str()을 취해서 키에 얘도 저장한다

- 그러면 다시 질문을 번호로 받았을 때도 출력할 수 있다
"""

N, M = map(int, input().split())

dogam = {}

#애초에 도감에 저장을 둘다 해놓는다..
for n in range(1,N+1):
    name = input()
    dogam[str(n)] = name
    dogam[name] = str(n)

for _ in range(M):
    question = input()
    print(dogam[question])