# -*- coding: utf-8 -*-
"""백준 1977 (완전제곱수)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GlwhuLg40EuZRPoZ6z0x6Lh-9jC76S6f
"""

# 함수를 지정해 줄 필요가 없다...
def Issquare(n):
    issquare = True
    i = 2
    while n > 1:
        if n % i == 0 :
            if n % (i*i) != 0:
                issquare = False
                break
            else :
                n = n // (i*i)
        else :
            i = i + 1
    return issquare

M = int(input())
N = int(input())

square = []
sum = 0
for _ in range(M, N+1):
    if Issquare(_) is True :
        sum += _
        square.append(_)

if sum == 0:
    print(-1)
else :
    print(sum)
    print(square[0])

#완전제곱을 판단할 필요가 없이 그냥 하면 된다

M = int(input())
N = int(input())

square = []
i = 1
sum = 0
while i**2 < N+1:
    if M <= i**2 <= N:          #이게 되네..
        square.append(i**2)
        sum += i**2
    i += 1

if square == []:
    print(-1)

else :
    print(sum)
    print(square[0])
#sum(square)가 왜 안대지...

