# -*- coding: utf-8 -*-
"""백준 10996 (별찍기 - 21)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11sEq3zuDpIM47ay1jHdTeKr-WzKvpZBX
"""

N = int(input())

if N == 1:
    print("*")
else:
    for i in range(2*N):
        if i%2 == 0:
            print("* "*((N+1)//2))
        else:
            print(" *"*(N//2))

