# -*- coding: utf-8 -*-
"""백준 10991 (별찍기 - 16)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1weT7tA_FJ7hYGDNd6Lpeb_m-zQqf8XYN

빨래집게 모양 + 안에 하나씩 별찍기..
"""

N = int(input())

if N % 2 == 1:
    if N == 1:
        print("*")
    else :
        for i in range(N):  # i : 0 ~ 3
            print(" "* (N - (i+1)), end = "")
            for j in range(N-(i+1) ,N+i):    # j : 3~3 / 2 N-(i+1) 부터 N+i까지
                if (i+j) % 2 == 1:
                    print(" ", end = "")
                else:
                    print("*", end = "")
            print()
else:
    for i in range(N):  # i : 0 ~ 3
        print(" "* (N - (i+1)), end = "")
        for j in range(N-(i+1) ,N+i):    # j : 3~3 / 2 N-(i+1) 부터 N+i까지
            if (i+j) % 2 == 1:
                print("*", end = "")
            else:
                print(" ", end = "")
        print()

# '* '가 반복되는 모양이라고 보면 된다..
#지리네..

N=int(input())
for i in range(1,N+1):
    print(' '*(N-i)+'* '*i)