# -*- coding: utf-8 -*-
"""백준 2442 (별찍기 - 5)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13qDcwgrcuQvPVYzTg08L1pTpKGeOodXI

첫째 줄에는 별 1개, 둘째 줄에는 별 3개, ..., N번째 줄에는 별 2×N-1개를 찍는 문제

별은 가운데 대칭..
"""

N = int(input())

for i in range(N):
    print(" "*(N-(i+1)) + "*"*(i+1) + "*"*(i))

N = int(input())

for i in range(N):
    print(" "*(N-(i+1)) + "*"*(2*i+1))

