# -*- coding: utf-8 -*-
"""백준 10992 (별찍기 - 17)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19EX78FyX0RKpAaOmQgnMGq4RpUq65gig
"""

N = int(input())

for i in range(N-1):
    if i==0:
        print(" "*(N-(i+1)) + "*")
    else :
        print(" "*(N-(i+1)) + "*" + " "*(2*i-1) + "*")
print("*"*(2*N - 1))

