# -*- coding: utf-8 -*-
"""백준 2522 (별찍기 - 12)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zT9kyu25_jdTRMDFlwoFxUP2fYDkFyka

첫째 줄부터 2×N-1번째 줄까지 차례대로 별을 출력한다.

ex) 입력이 3이면 1 - 2 - 3 - 2 - 1 순서로 별 출력..
"""

N = int(input())

for i in range(N):
    print(" "*(N-(i+1)) + "*"*(i+1))
#3까지 출력..

for i in range(1,N):
    print(" "*i + "*"*(N-i))

