# -*- coding: utf-8 -*-
"""백준 2446 (별찍기 -  9)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14JL1o_HnH5mDxV1BlXNe4mLqY0HCrSOy

모래시계모양으로..

9 - 7 - 5 - 3 - 1 - 3 - 5 - 7 - 9..
"""

N = int(input())

for i in range(N):
    print(" "*i + "*"*(2*N - (2*i + 1)))
#별 하나까지 출력됨..

for i in range(1, N):
    print(" "*(N - (i+1)) + "*" * (2*i + 1))

