# -*- coding: utf-8 -*-
"""백준 10990 (별찍기 - 15)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lDTsD8CeTHsNJcyhgTI5WzGjqxZgZloP

빨래집게 모양으로..

중간에 1 - 3 - 5 - ...이렇게 점점 중간 공백을 늘려간다..
"""

N = int(input())

for i in range(N):
    if i==0:
        print(" "*(N-1) + "*")
    else :
        print(" "*(N-(i+1)) + "*" + " "*(2*i - 1) + "*")

