# -*- coding: utf-8 -*-
"""백준 2438 (별찍기 - 1)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u6Cff8RMAkV2VJR4CJDRCkFfqhExbh9x

첫째줄에는 별 1개, 둘째줄에는 2개... N번째줄에는 N개를 찍어라..
"""

N = int(input())

for i in range(N):
    print("*" * (i+1))

