# -*- coding: utf-8 -*-
"""백준 13015 (별찍기 - 23)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OtxFuzjkV9TP9zbRZygIdgLME6CyDKyf

X 모양으로 별찍기..
"""

N = int(input())

for i in range(N-1):
    if i == 0:
        print("*"*N + " "*(2*N-3) + "*"*N)
    else:
        print(" "*i + "*" + " "*(N-2) + "*" + " "*(2*N - 2*i - 3)+"*" + " "*(N-2)+"*")

for i in range(N):
    if i == N-1:
        print("*"*N + " "*(2*N-3) + "*"*N)
    elif i == 0:
        print(" "*(N-(i+1)) + "*" + " "*(N-2) + "*" + " "*(N-2)+"*")
    else:
        print(" "*(N-(i+1)) + "*" + " "*(N-2) + "*" + " "*(2*i - 1) + "*" + " "*(N-2)+"*")