# -*- coding: utf-8 -*-
"""백준 2445 (별찍기 - 8)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ogUUZRmvY3Gxkz0ZRH-qBUQljcGERt4C

첫째 줄부터 2×N-1번째 줄까지 차례대로 별을 출력한다.

나비 날개 모양..

별 - 공백 - 별

- 1차 포문..

1 - 8 - 1

2 - 6 - 2

3 - 4 - 3

4 - 2 - 4

5 - 0 - 5

- 2차 포문..

4 - 2 - 4

3 - 4 - 3

2 - 6 - 2

1 - 8 - 1
"""

N = int(input())

for i in range(N):
    print("*"*(i+1) + " "*(2*N - 2*(i+1)) + "*"*(i+1))
for i in range(N):
    print("*"*(N-(i+1)) + " "*(2*(i+1)) + "*"*(N-(i+1)) )

