# -*- coding: utf-8 -*-
"""백준 10995 (별찍기 - 20)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p5wHiWWgSiiNQSUJy0cfXj9gBZuMMeTI
"""

N = int(input())

for i in range(N):
    if i%2 == 0:
        for j in range(2*N - 1):
            if j%2 == 0:
                print("*", end = "")
            else:
                print(" ", end = "")
    else:
        for j in range(2*N):
            if j%2 == 0:
                print(" ", end = "")
            else:
                print("*", end = "")
    print()

