# -*- coding: utf-8 -*-
"""백준 2443 (별찍기 - 6)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TaA4X8khuphZzXEUzuUxQwfejCyhY6iY

첫째 줄에는 별 2×N-1개, 둘째 줄에는 별 2×N-3개, ..., N번째 줄에는 별 1개를 찍는 문제

별은 가운데 대칭..
"""

N = int(input())

for i in range(N):
    print(" " * i + "*" * (2 * N - (2 * i + 1)))

