# -*- coding: utf-8 -*-
"""백준 2439 (별찍기 - 2)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sUjVcTMWBHRfdnc1dEacCN3YK3dHRldM

첫째 줄에는 별 1개, 둘째 줄에는 별 2개, N번째 줄에는 별 N개를 찍어라..

우측정렬..
"""

N = int(input())

for i in range(N):
    print(" " * (N-(i+1)) + "*" * (i+1))

