# -*- coding: utf-8 -*-
"""백준 15596 (정수 N개의 합)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JwBmreqhciSs7CL0WBLnIq7VucXCclig
"""

def solve(a):
    sum = 0
    for i in a:
        sum += i
    print(sum)

