# -*- coding: utf-8 -*-
"""백준 10773 (제로)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x4DtzUAz0fgiL8BcmukQmkn9KYzP9B9K

**문제**

- K 개의 정수가 주어짐
- 정수가 0일 경우에 가장 최근의 수를 지우고, 아닐 경우 해당 수를 쓴다..
- 최종적으로 적어낸 수의 합을 출력

**풀이**

- 리스트와 sum을 동시에 계산한다
- 정수가 0이면 pop하고 sum에서도 뺀다..
"""

K = int(input())

sum = 0
numsList = []
for i in range(K):
    num = int(input())
    if num == 0:
        sum -= numsList.pop()
    else:
        numsList.append(num)
        sum += numsList[-1]

print(sum)

