# -*- coding: utf-8 -*-
"""백준 1436 (영화감독 숌)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12gbFrsDOd7-q6t9QPpOjKLELna5CC3ii

**문제**

- 종말의 숫자 : 6이 적어도 3개이상 연속으로 들어가는 수
- N이 주어지면 N번째로 작은 종말의 숫자를 출력한다

**풀이**

- N을 줄이면서 다음 종말의 숫자를 찾아간다..
- 문자열로 찾으면 된다!!
"""

#N을 줄이면서 종말의 숫자를 찾아간다..
N = int(input())

num = 666

while (N > 0):
    if '666' in str(num):
        N -= 1
    num += 1

print(num - 1)

# 반례 : 1116661111 같은 수는 찾지 못한다..

T = int(input())

for _ in range(T):
    N = int(input())

    q = (N) // 19
    r = (N) % 19

    if r == 0:
        print(((q-1)*10 + 9)*1000 + 666)
    elif 7 <= r <= 16:
        print((q*10 + 6) * 1000 + 660 + (r-7))
    elif r <= 6:
        print((q*10 + r-1) * 1000 + 666)
    else:
        print((q*10 + r%10) * 1000 + 666)

N = int(input())

q = (N-1) // 19
r = (N-1) % 19

if 6 <= r <= 15:
    print((q*10 + 6) * 1000 + 660 + (r-6))
elif r < 6:
    print((q*10 + r) * 1000 + 666)
else:
    print(((q*10) + (r+1)%10) * 1000 + 666)