# -*- coding: utf-8 -*-
"""백준 1316 (그룹 단어 체커)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rrZj2e2QVylPsBNLpOud0upiFtEN4DOZ

**풀이**

- 어떤 문자가 마지막으로 나온 번째수를 딕셔너리에 저장한다
"""

N = int(input())
cnt = 0

for _ in range(N):
    word = input()
    Isgroup = True
    checker = {}
    for i in range(len(word)):
        #하나씩 보는데, 알파벳이 checker의 키에 있으면..
        if word[i] in checker:
            if i - checker[word[i]] == 1:
                checker[word[i]] = i
            else:
                Isgroup = False
                break
        else:
            checker[word[i]] = i

    if Isgroup:
        cnt += 1
print(cnt)

