# -*- coding: utf-8 -*-
"""백준 1152 (단어의 개수)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GAF85ki4pJ7LjfvR75KuRCg3-Ae51BgR
"""

sentence = list(input().split())

print(len(sentence))

