# -*- coding: utf-8 -*-
"""백준 1051 (숫자 정사각형)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FbOCdhuPYj3cu_F-WPKUiyTxjiKE8Lut
"""

N, M = map(int, input().split())
nums = []

"""
#리스트에 담기..
for j in range(N):
    num = int(input())
    for i in range(M-1,-1,-1):
        nums[j][i] = num % 10
        num = num // 10
"""
for _ in range(N):
    nums.append(input())

#큰거 찾기..
if N>M:
    big = N
    small = M
else:
    big = M
    small = N

print(nums)
found = False
#한변의 길이를 줄여가면서 확인한다..
for i in range(small, 0, -1):
    #좌표를 찍어가며 확인..
    for j in range(N-i+1):
        for k in range(M-i+1):
            #꼭짓점 확인..
            if nums[j][k] == nums[j+i-1][k] == nums[j][k+i-1] == nums[j+i-1][k+i-1]:
                max_len = i
                found = True
                break
        if found:
            break
    if found:
        break

print(max_len**2)

for i in range(1):
    print(i)

