# -*- coding: utf-8 -*-
"""백준 3052 (나머지)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Uaie86r62-VqGyFpfU6SrocB8buJvUXB

수 10개를 입력받은 뒤, 이를 42로 나눈 나머지를 구한다. 그 다음 서로 다른 값이 몇 개 있는지 출력하는

- 나머지가 나왔는지 알려주는 리스트를 하나 만든다
- 입력 받을때마다 리스트를 확인해서 cnt를 올린다
"""

check = [False] * 42

cnt = 0
for _ in range(10):
    num = int(input())
    if check[num % 42] is False:
        check[num % 42] = True
        cnt += 1
print(cnt)

