# -*- coding: utf-8 -*-
"""백준 1546 (평균)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GL1cMGDmVmNH7e9KWKJ4yIq5K_mJ2apZ

**문제**

- 점수 중 최고점 : M
- 다른 모든 점수를 (점수) / M * 100으로 바꿈
- 새로운 평균은?

**풀이**
- 원래 수 : a, b, c
- 원래 합 : a + b + c

- 나중 수 : a/c * 100, b/c * 100, c/c * 100
- 나중 합 : a/c * 100 + b/c * 100 + c/c * 100

1) 즉 나중 합이 (100/c) * (a + b + c)이 된다..

2) 평균은 원래 평균의 (100 / c)배가 된다
"""

N = int(input())
score = list(map(int, input().split()))
sum = 0
for num in score:
    sum += num
avg = sum / N
largest = max(score)

new_avg = avg * 100 / largest
print(new_avg)

