# -*- coding: utf-8 -*-
"""백준 1000 (A+B)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_nU0REwd0PI9OYywN98qUdGFygckUuMR
"""

A, B = map(int, input().split())

print(A+B)

