# -*- coding: utf-8 -*-
"""백준 1003 (피보나치 함수)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p4191LzeEqNbbtOvbWlzzI-GgCHOfitY

**풀이**

- fibonacci(0), fibonacci(1)의 호출횟수도 피보나치 수열을 따른다..
- 0의 호출횟수 : 1 0 1 1 2 3 5 ...
- 1의 호출횟수 : 0 1 1 2 3 5 8 ...
"""

T = int(input())

for _ in range(T):
    N = int(input())
    if N == 0:
        print(1, 0)
    elif N == 1:
        print(0, 1)
    else:
        a, b = 0, 1
        for _ in range(N-1):
            a, b = b, a + b
        print(a, b)

#시간초과..

def fibonacci(N):
    if N == 0:
        fib[0] += 1
        #print("0")
        return 0
    elif N == 1:
        fib[1] += 1
        #print("1")
        return 1
    else:
        return fibonacci(N-1) + fibonacci(N-2)

T = int(input())

for _ in range(T):
    N = int(input())
    fib = [0, 0]
    fibonacci(N)
    print(fib[0], fib[1])