# -*- coding: utf-8 -*-
"""백준 1001 (A-B)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eHQnN1VKTJYh2u_jpk63SNBGBIv6myhx
"""

A, B = map(int, input().split())

print(A-B)

