# -*- coding: utf-8 -*-
"""백준 1008번 (A/B)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dM9RzrLqQyTCh-pgqYeE1qKvcB3em9M1
"""

A, B = map(int, input().split())

print(A/B)

