# -*- coding: utf-8 -*-
"""백준 8958 (OX퀴즈)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19lCV3RUttMjOlAZjrvWW1IbsrdcsZxQ7

**문제**

- 문제를 맞은 경우 그 문제의 점수는 그 문제까지 연속된 O의 개수가 된다. 
- "OOXXOXXOOO"의 점수는 1+2+0+0+1+0+0+1+2+3 = 10점이다.

**아이디어**
- 몇 개 연속으로 맞췄는지 알아야한다
"""

T = int(input())

for _ in range(T):
    result = input()
    cnt = 0
    sum = 0
    for i in range(len(result)):
        if result[i] == 'O':
            cnt = cnt + 1
        else :
            cnt = 0
        sum += cnt
    print(sum)