# -*- coding: utf-8 -*-
"""백준 5347 (LCM)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ApYnBtMxZW7ecbylZWsJtklXMbEiaSU3

**문제**

- a, b가 주어질때 두 수의 최소 공배수를 구하라
"""

T = int(input())

for _ in range(T):
    a,b = map(int, input().split())

    if a>b:
        big = a
        small = b
    else:
        big = b
        small =a

    while (small > 0):
        big, small = small, big % small

    print(a*b//big)

