# -*- coding: utf-8 -*-
"""백준 1427 (소트인사이드)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ODiTGc5XV-pWwm3eiDQqbrBw-8Z0QoJZ

**문제**

- 입력을 내림차순으로 정렬해서 출력하라
"""

N = input()
nums = []
for i in range(len(N)):
    nums.append(N[i])
nums.sort(reverse = True)
for i in nums:
    print(i, end = "")