# -*- coding: utf-8 -*-
"""백준 1065 (한수)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10mzKJfBfaDQSqVfOb5CKqPtOAo3pMHLL
"""

N = int(input())

if N <100:
    print(N)
else:
    cnt = 99
    for i in range(100, N+1):
        if i//100 - (i%100)//10 == (i%100)//10 - i%10:
            cnt += 1   
    print(cnt)

