# -*- coding: utf-8 -*-
"""백준 11720 (숫자의 합)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11O-f_Zvy5lzswlWmrp9NKGiWR9cr6jR6
"""

N = int(input())
nums = input()

sum = 0
for i in range(N):
    sum += int(nums[i])
print(sum)

