# -*- coding: utf-8 -*-
"""백준 1157 (단어 공부)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1roYFGRi5TMRE-pTAIb2YozO_P6tQIKLi

**문제**

- 단어가 주어지면 가장 많이 나온 알파벳을 대문자로 바꿔서 출력
- 가장 많이 나온게 여러개면 ? 출력

**풀이**

- 딕셔너리에 저장
- 정렬은 lambda..
"""

word = input()
word = word.upper()

Note = {}

for i in word:
    if i in Note:
        Note[i][1] += 1
    else:
        Note[i] = [i, 1]

Note = sorted(Note.values(), key=lambda x : x[1], reverse=True)

if len(Note) == 1:
    print(Note[0][0])
else:
    if Note[0][1] == Note[1][1]:
        print('?')
    else:
        print(Note[0][0])