# -*- coding: utf-8 -*-
"""백준 2750 (수 정렬하기)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11N2LETP_AeyCJoDxREfFq_s5JwUJZxYE
"""

N = int(input())
nums = [0] * N
for i in range(N):
    nums[i] = int(input())
nums.sort()
for num in nums:
    print(num)

