# -*- coding: utf-8 -*-
"""백준 18883 (N M 찍기)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QAbRNsnNGRD_TJrGUIUpBT-DMDO5_e3j
"""

N, M = map(int, input().split())

for i in range(1, N*M + 1):
    if (i % M == 0):
        print(i)
    else :
        print(i, end = ' ')

# 셀 필요 자체가 없네...