# -*- coding: utf-8 -*-
"""백준 2747 (피보나치 수)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X65sCIUazo9vWTJv7kg_x0hhkzTcUO82
"""

def fib(n):
    if n < 2:
        print(n)
    else :
        a = 0
        b = 1
        for i in range(1,n):
            a, b = b, a+b        
        print(b)

n = int(input())
fib(n)