# -*- coding: utf-8 -*-
"""백준 2609 (최대공약수와 최소공배수)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RWHTuEQWwLrgRAliocAkmpVedcBAU83e
"""

#백준 2609
def gcd(a,b):
    while b > 0:
        a, b = b, a%b  
    return a

def lcm(a,b):
    gcd1 = gcd(a,b)
    lcm = int(a * b / gcd1)
    return lcm

m, n = map(int, input().split())
print(gcd(m,n))
print(lcm(m,n))