# -*- coding: utf-8 -*-
"""백준 2309 (일곱 난쟁이)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lY-ZY1lDKVkocCWg7p3pHQLGIKyBKVyv

#모든가짓수를 어떻게 다 확인할까?

**프로그래머스에서 자연스럽게 풀었다!**

[mCn의 모든 조합을 확인하는 중첩 for문](https://github.com/dong-tak123/Self_Study/blob/main/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4/Python3/%EC%86%8C%EC%88%98_%EB%A7%8C%EB%93%A4%EA%B8%B0.py)
"""

# 1)일단 모든 난쟁이의 키를 입력받아서 height리스트에 넣고 전체합도 계산한다
height = []
sum = 0
for _ in range(9):
    ki = int(input())
    height.append(ki)
    sum += ki

# 2)정렬이고 나발이고 일단 뭐가 맞는지 확인한다..
# 여기서 2중 포문으로 다 확인한다.. 안들어가는거 2개를 찾는다고 생각.
for i in range(8):
    for j in range(i+1, 9):
        if (sum - height[i]- height[j] == 100):
            no_seven = [height[i], height[j]]
            break

height.remove(no_seven[0])
height.remove(no_seven[1])
height.sort()

for k in range(7):
    print(height[k])

1#36번의 경우만 다 해보면 되지 않을까?

height = []
real_seven =[]

for i in range(9):
    height.append(int(input()))
height.sort(reverse = True)

sum = 0
for x in height:
    if sum + x <= 100:
        real_seven.append(x)
        sum = sum + x
        if sum == 100 and len(real_seven) == 7 :
            break

for c in real_seven:
    print(c)

