# -*- coding: utf-8 -*-
"""백준 1978 (소수찾기)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1siRMAYFMLSAqmX0yohXNG_HVWCyr2djK
"""

def IsPrime(n):
    if n == 1:
        return False
    elif n < 4:
        return True
    else :
        Isprime = True
        for i in range(2,n):
            if n % i == 0 :
                Isprime = False
                break
        return Isprime

N = int(input())
numbers = list(map(int, input().split()))
count = 0

for m in numbers:
    if IsPrime(m) is True:
        count += 1
print(count)

