# -*- coding: utf-8 -*-
"""백준 10867 (중복 빼고 정렬하기)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zL1Aw7ggTWmljq25DKR4MF0SOdgzFy-G

**문제**

- 오름차순으로 정렬하되 중복된건 출력하지마라

**풀이**

- set 자료구조를 쓰자..
"""

N = int(input())

nums = list(set(map(int, input().split())))

nums.sort()
for i in nums:
    print(i, end = " ")

