# -*- coding: utf-8 -*-
"""백준 4948 (베르트랑 공준)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13r9izsp3vw5dPX9wqqu2ghJJpHqwbs72

**문제**

- 임의의 자연수 n에 대하여 n보다 크고 2n보다 작거나 같은 소수의 갯수를 출력하라

**풀이**

- 1. dp 만들기..
- 2. 소수 판정 함수 만들기..
"""

#입력 때 마다 dp를 만드니까 엄청 시간이 오래걸린다..
#한번최대값 까지 만들어놓고 사용도 가능

while True:
    n = int(input())
    if n == 0:
        break
    dp = [False, False] + [True] * (2*n-1)
    for i in range(2, 2*n+1):
        if dp[i]:
            for j in range(2*i, 2*n+1, i):
                dp[j] = False

    num = 0
    for i in range(n+1, 2*n+1):
        if dp[i]:
            num += 1
    print(num)

#입력 때 마다 dp를 만드니까 엄청 시간이 오래걸린다..
#한번최대값 까지 만들어놓고 사용도 가능

#한번 만들기.. 최대 n : 123456
max = 123456
dp = [False, False] + [True] * (2*max-1)
for i in range(2, int((2*max)**0.5) + 1):
    if dp[i]:
        for j in range(2*i, 2*max+1, i):
            dp[j] = False

while True:
    n = int(input())
    if n == 0:
        break
    
    num = 0
    for i in range(n+1, 2*n+1):
        if dp[i]:
            num += 1
    print(num)

1