# -*- coding: utf-8 -*-
"""백준 1764 (듣보잡)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e-hxC_FChzuY69TBSsl9ZHZ5PYudyPCu

**문제**

- 듣도 못한 사람 수 N, 보도 못한 사람 수 M이 주어짐
- 그 이후로 사람 N명, M명 입력
- 듣도 보도 못한 사람 사전 순 출력

**풀이**
- 자료구조 셋을 이용 ( {}괄호 사용 )
- 딕셔너리를 이용한 add가 더 빠름(아주 조금)
"""

#딕셔너리로 입력받아서 키 값만 intersection한 뒤 리스트로 변경

N, M = map(int, input().split())

never_heard = {}
never_seen = {}

for _ in range(N):
    never_heard[input()] = 1

for _ in range(M):
    never_seen[input()] = 1

never_heard_seen = list(never_heard.keys() & never_seen.keys())

l = len(never_heard_seen)
print(l)

never_heard_seen.sort()
for i in range(l):
    print(never_heard_seen[i])

#셋으로 입력받아서 intersection한 뒤 리스트로 변경

N, M = map(int, input().split())

never_heard = set()
never_seen = set()

for _ in range(N):
    never_heard.add(input())

for _ in range(M):
    never_seen.add(input())

never_heard_seen = list(never_heard & never_seen)

l = len(never_heard_seen)
print(l)

never_heard_seen.sort()
for i in range(l):
    print(never_heard_seen[i])