# -*- coding: utf-8 -*-
"""백준 1292 (쉽게 푸는 문제)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qM7MRVXFdHTJ0jVy5xkjU_L5V0IKFsiD
"""

def calculate_sum(N):
    i = 1
    sum = 0
    while 1:
        #i는 i(i+1)//2번째 까지 있다..
        if i*(i+1)//2 < N+1:
            sum += i*i
            i += 1
        #i를 끝까지 담기에는 부족했다..
        else:
            sum += i*(N - i*(i-1)//2)
            break
    return sum

A, B = map(int, input().split())

print(calculate_sum(B)- calculate_sum(A-1))

