# -*- coding: utf-8 -*-
"""백준 10845 (큐)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14a1xCvpmWtDJUaUJ516ZbjQxAyEUasG8
"""

def push(a):
    queue.append(a)

def pop():
    if queue:
        print(queue[0])
        del queue[0]
    else:
        print(-1)

def size():
    print(len(queue))

def empty():
    if queue:
        print(0)
    else:
        print(1)

def front():
    if queue:
        print(queue[0])
    else:
        print(-1)

def back():
    if queue:
        print(queue[-1])
    else:
        print(-1)

N = int(input())
queue = []
for _ in range(N):
    command = input().split()
    if command[0] == "push":
        push(command[1])
    elif command[0] == "pop":
        pop()
    elif command[0] == "size":
        size()
    elif command[0] == "empty":
        empty()
    elif command[0] == "front":
        front()
    elif command[0] == "back":
        back()