# -*- coding: utf-8 -*-
"""백준 1181 (단어 정렬)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PLptiq29QUykz3t_UHWG3PxPWji8uEC6

**문제**

- 단어 입력 받기
- 길이순..
- 같으면 사전순..

**풀이**

- 딕셔너리의 유용함..
"""

N = int(input())
note = {}
for _ in range(N):
    word = input()
    if word not in note:
        note[word] = [len(word), word]

note = sorted(note.values(), key = lambda x : (x[0], x[1]))
for i in note:
    print(i[1])

