# -*- coding: utf-8 -*-
"""백준 1629 (곱셈)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v8BaOFGJ9ssvhW-E9OrtdAVHipH2vVHE

**문제**

- 자연수 A를 B번 곱한 수를 알고 싶다
- 이를 C로 나눈 나머지를 구하시오

**풀이**
- 분할정복..
- 재귀적이라 생각 필요..
- 루트씩 해서 시간복잡도가 $log_2n$이 된다..
"""

A, B, C = map(int, input().split())

def Divide_Conquer(a,b):
    if b==1:
        return a%C
    
    temp = Divide_Conquer(a, b//2)

    if b%2 == 0:
        #짝수면 제곱해서 반환
        return temp*temp % C
    else:
        #홀수면 제곱하고 한번더 곱해서 반환
        return temp*temp*a % C

print(Divide_Conquer(A, B))

"""- 반복문으로 하면 절대 안된다.. 시간때문에.."""

A, B, C = map(int, input().split())

while (B > 0):
    temp = A ** (B//2)
    if B % 2 == 0:
        A = temp ** 2 % C
    else:
        A = temp * temp * A % C
    print(temp, A)

    B = B//2

print(A % C)