# -*- coding: utf-8 -*-
"""백준 2960 (에라토스테네스의 체)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EBoOxK8gk4wvngFzZuQHcElW1vFOHSWo

**에라토스테네스의 체**

- N보다 작거나 같은 모든 소수를 찾는  알고리즘

1) 2부터 N까지 모든 정수를 적는다.

2) 아직 지우지 않은 수 중 가장 작은 수를 찾는다. 이것을 P라고 하고, 이 수는 소수이다.

3) P를 지우고, 아직 지우지 않은 P의 배수를 크기 순서대로 지운다.

4) 아직 모든 수를 지우지 않았다면, 다시 2번 단계로 간다.

**주의**

- 지웠던 거를 또 지우면 안되니까 if문이 한번 더 있어야 한다..
"""

N, K = map(int, input().split())

dp = [True] * (N+1)
cnt = 0
for i in range(2, N+1):
    if dp[i]:
        for j in range(i, N+1, i):
            #중복으로 지우기 방지 
            if dp[j]:
                dp[j] = False
                cnt += 1
                if (cnt == K):
                    print(j)
                    break
    if (cnt == K):
        break

