# -*- coding: utf-8 -*-
"""백준 1158 (요세푸스 문제)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DBR6ovqSbU-MMZFjOzt5q6qWIt4PrEst

**문제**

- 1번부터 N번까지 N명의 사람이 원을 이루면서 앉아있고, 순서대로 K번째 사람을 제거한다..
- N명의 사람이 모두 제거될 때 까지 계속된다..
- 원에서 사람들이 제거되는 순서 : 요세푸스 순열
"""

a = [1,2,3,4,5,6,7,1,2,3,4,5,6,7,1,2,3,4,5,6,7]

for i in range(len(a)):
    if (i+1) % 3 == 0:
        print(a[i])

b = [1,2,3,4,5,6]

[1,2,4,5,6]
[1,2,4,5]
[1,2,5]
3->6->