# -*- coding: utf-8 -*-
"""백준 11656 (접미사 배열)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-Bh-Qe3Ut8mYmhBH_L2dFqBaJVzl9s70

**문제**

- 문자열의 접미사를 사전순으로 정렬한 다음 출력하라

**풀이**

- 문자열의 인덱싱으로 모든 접미사를 리스트에 추가한다
- sort()를 사용해서 사전순으로 정렬하고 출력한다
"""

S = input()

tail = []
for i in range(len(S)):
    tail.append(S[i:])

tail.sort()
for i in tail:
    print(i)

