# -*- coding: utf-8 -*-
"""백준 1049 (기타줄)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10sGQOp9Xly8Xxkz2JKPOf7Wif7NRU77J

필요한 세트갯수와 낱개의 수를 계산하고

각 경우에 최소 금액으로 사면 얼마를 내야하는지도 if elif else문으로 계산한다
"""

N, M = map(int, input().split())

N_sets = N // 6
N_natgae = N % 6

Sets=[]
Natgae=[]
for _ in range(M):
    sets_price, natgae_price = map(int, input().split())
    Sets.append(sets_price)
    Natgae.append(natgae_price)

min_set_price = min(Sets)
min_natgae_price = min(Natgae)


if min_set_price > 6*min_natgae_price:      #세트가격이 낱개 6개보다 비쌀때
    print(N * min_natgae_price)
elif min_set_price < N_natgae * min_natgae_price:      #세트가격이 내가사야하는 낱개합한거보다 쌀때
    #세트만 사면됨..
    print((N_sets+1)*min_set_price)
else:
    print(min_set_price * N_sets + min_natgae_price * N_natgae)

import sys
N, M = map(int,sys.stdin.readline().split())
p = [0]*2       #세트와 낱개 가격의 최소값을 저장할 길이가 2인 리스트 p
c = 1001        #젤 큰걸 두고 시작
d = 1001        #젤 큰걸 두고 시작..
s = 0
for _ in range(M):
    a,b = map(int, sys.stdin.readline().split())
    if a < c:
        p[0]=a
        c = a       #하면서 바로바로 최솟값을 지정..
    if b < d:
        p[1]=b
        d = b

# 내 풀이의 if elif else 구문..
p1 = ((N//6)+1)*p[0]
p2 = (N//6)*p[0] + (N%6)*p[1]
p3 = N*p[1]
s = min(p1,p2,p3)
print(s)