# -*- coding: utf-8 -*-
"""백준 10866 (덱)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kHUr_vroU96a_3efPlV1hKaXvud9KrEa

**문제**

- 데크 자료구조를 직접 구현하라..

**풀이**

- collections에서 deque를 가져와서 메서드를 사용..
"""

from collections import deque

def push_front(x):
    seq.appendleft(x)
def push_back(x):
    seq.append(x)
def pop_front():
    if seq:
        print(seq.popleft())
    else:
        print(-1)
def pop_back():
    if seq:
        print(seq.pop())
    else:
        print(-1)
def size():
    print(len(seq))
def empty():
    if seq:
        print(0)
    else:
        print(1)
def front():
    if seq:
        print(seq[0])
    else:
        print(-1)
def back():
    if seq:
        print(seq[-1])
    else:
        print(-1)

N = int(input())
seq = deque()

for _ in range(N):
    command = input().split()
    if command[0] == "push_front":
        push_front(command[1])
    elif command[0] == "push_back":
        push_back(command[1])
    elif command[0] == "pop_front":
        pop_front()
    elif command[0] == "pop_back":
        pop_back()
    elif command[0] == "size":
        size()
    elif command[0] == "empty":
        empty()
    elif command[0] == "front":
        front()
    elif command[0] == "back":
        back()

