# -*- coding: utf-8 -*-
"""백준 5052 (전화번호 목록)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gRj22IROOZQKttiBYr9Pntztu_tHGzzJ

**문제**

- 전화번호가 다른 전화번호의 접두사가 되면 안된다..

**풀이**

- 입력을 미리 다 받고
- **전화번호부를 정렬을 하면 바로 뒤 번호와 비교만 하면 된다**
    - 시간단축에 좋다
- 길이만으로 비교하면 안된다!!
- 실제로 같은지 비교해야함..
"""

#시간초과로 인한 Pypy3 실행

T = int(input())
for _ in range(T):
    N = int(input())
    phone_book = []
    consistency = True

    #입력을 미리 다 받고
    for i in range(N):
        phone_number = input()
        phone_book.append(phone_number)

    #정렬을 하면 바로 뒤에 것과만 체크하면됨..
    phone_book.sort()
    for i in range(N-1):
        if phone_book[i+1][:len(phone_book[i])] == phone_book[i]:
            consistency = False
            break

    #일관성에 따라 확인
    if consistency:
        print("YES")
    else:
        print("NO")

# 길이로 확인했기 때문에 오류가 있었음..

T = int(input())
for _ in range(T):
    N = int(input())
    phone_book = []
    consistency = True
    for i in range(N):
        phone_number = input()
        phone_book.append(phone_number)
    phone_book.sort()
    for i in range(N):
        for j in range(i):
            if len(phone_book[i].lstrip(phone_book[j])) == len(phone_book[i]) - len(phone_book[j]):
                consistency = False
                break
    if consistency:
        print("YES")
    else:
        print("NO")

