# -*- coding: utf-8 -*-
"""백준 5430 (AC)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14SLWj8DTDIbgDrrV8RDyGTU3Fbl7Y4YL

**문제**

- R : 뒤집기  /  D : 버리기
- 배열이 비어있는데 D를 사용하면 error
- 함수는 조합해서 한번 쓸 수 있음

**풀이**

- 앞 뒤에서 다 빠질 수 있는 데크 자료구조가 필요하다..
- 데크 자료구조가 없으면 시간초과..
"""

from collections import deque
T = int(input())

for _ in range(T):
    p = input()
    p.replace("RR","")
    #배열 안의 숫자의 갯수 n
    n = int(input())
    arr = deque(list(input().rstrip(']').lstrip('[').split(',')))
    
    num_R = 0
    flag = True
    #arr의 짝수 인덱스가 숫자임
    for i in p:
        if i == 'R':
            num_R += 1
        else:   #D일 때
            if n == 0:
                flag = False
                break

            if num_R % 2 == 1:
                #뒤에 거 부터 없에야함
                arr.pop()
            else:
                arr.popleft()
            n -= 1
    if flag:
        if num_R % 2 == 0:
            print('[' + ",".join(arr) + ']')
        else:
            arr.reverse()
            print('[' + ",".join(arr) + ']')
    else:
        print('error')

#아마 시간초과...
# 채점중 50퍼센트까지...
# R의 갯수를 세어보자..

T = int(input())

for _ in range(T):
    p = input()
    p.replace("RR","")
    #배열 안의 숫자의 갯수 n
    n = int(input())
    arr = list(input().rstrip(']').lstrip('[').split(','))
    
    num_R = 0
    flag = True
    #arr의 짝수 인덱스가 숫자임
    for i in p:
        if i == 'R':
            num_R += 1
        else:   #D일 때
            if n == 0:
                flag = False
                break

            if num_R % 2 == 1:
                #뒤에 거 부터 없에야함
                arr.pop()
            else:
                arr.reverse()
                arr = arr[1:]
                arr.reverse()
            n -= 1
    if flag:
        if num_R % 2 == 0:
            print('[' + ",".join(arr) + ']')
        else:
            arr.reverse()
            print('[' + ",".join(arr) + ']')
    else:
        print('error')

#아마 시간초과...
# 채점중 50퍼센트까지...

T = int(input())

for _ in range(T):
    p = input()
    #배열 안의 숫자의 갯수 n
    n = int(input())
    arr = list(input().rstrip(']').lstrip('['))
    print(arr)

    flag = True
    #arr의 짝수 인덱스가 숫자임
    for i in p:
        if i == 'R':
            arr.reverse()
        elif i == 'D':
            if n == 0:
                flag = False
                break
            elif n == 1:
                arr.pop()
            else :
                arr = arr[2:]
            n -= 1

    if flag:
        print('['+"".join(arr)+']')
    else:
        print('error')

#아마 시간초과...
T = int(input())

for _ in range(T):
    p = input()
    #배열 안의 숫자의 갯수 n
    n = int(input())
    arr = input()
    arr = arr.rstrip(']').lstrip('[')
    arrList = list(arr)
    flag = True
    #arr의 짝수 인덱스가 숫자임
    for i in p:
        if i == 'R':
            arrList.reverse()
        elif i == 'D':
            if len(arrList) == 0:
                flag = False
                break
            else:
                if len(arrList) == 1:
                    arrList.pop()
                else :
                    arrList = arrList[2:]
    if flag:
        print('['+"".join(arrList)+']')
    else:
        print('error')

a = ['1','2','3']
a.reverse()
print(a)

