# -*- coding: utf-8 -*-
"""백준 7785 (회사에 있는 사람)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DhUaEfTx31OSCGEJBlsVWTOTVt2Va-LD

**문제**

- 출입 기록 주어짐
- 대소문자가 다르면 다른이름..
- enter 출근, leave 퇴근
"""

N = int(input())

member = {}
for _ in range(N):
    name, in_out = input().split()
    if in_out == 'enter':
        member[name] = 1
    else:
        if member[name]:
            del member[name]

member = sorted(member, reverse=True)
for i in member:
    print(i)