# -*- coding: utf-8 -*-
"""백준 11726 (2Xn 타일링)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LVaKuyMyKGbK0uGRf5SMiio5FkHua9K5

**문제**

- 2 * n 크기의 직사각형을 1 * 2, 2 * 1 타일로 채우는 방법의 수를 구하라..

**풀이**

- 마지막이 | 이거나 = 인 경우 두가지가 있다
    - | 인 경우 : 바로 앞의 가짓수와 똑같다
    - = 인 경우 : 바로 앞앞의 가짓수와 똑같다

- 관계식 : f(n) = f(n-1) + f(n-2)
"""

#피보나치 n번째 수를 출력..

n = int(input())

a, b = 0, 1

while n :
    a, b = b, a+b
    n -= 1

print(b % 10007)