# -*- coding: utf-8 -*-
"""백준 11650 (좌표 정렬하기)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14drW3Ze7YxMCN7Q5MGUn20zSVPTkEDIa

**문제**

- 2차원 평면의 점 N개가 주어짐
- 좌표를 x가 증가하는 순, y가 증가하는 순서로 정렬해서 출력해라

**풀이**

- 리스트에 입력받고
- sorted()함수 쓰면 야무지다
"""

N = int(input())
points = []
for _ in range(N):
    a, b = map(int, input().split())
    points.append([a,b])

#0번째 열, 1번째 열 (x, y) 순서로 정렬하자..
points_sorted = sorted(points, key = lambda x:(x[0],x[1]))

for i in range(N):
    print(points_sorted[i][0], points_sorted[i][1])