# -*- coding: utf-8 -*-
"""백준 1158 (요세푸스 문제)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DBR6ovqSbU-MMZFjOzt5q6qWIt4PrEst

**문제**

- 1번부터 N번까지 N명의 사람이 원을 이루면서 앉아있고, 순서대로 K번째 사람을 제거한다..
- N명의 사람이 모두 제거될 때 까지 계속된다..
- 원에서 사람들이 제거되는 순서 : 요세푸스 순열

**풀이**

- 1에서 N까지의 리스트를 만들고, 인덱스를 돌려가면서 출력
- 하나빼고 돌아가므로 인덱스가 K-1씩 증가함
- b라는 새로운 리스트에 없에는 걸 저장해놓고 한꺼번에 출력
"""

N, K = map(int, input().split())
a = list(range(1, N+1))
start = 0
b = []
while (a):
    start += K-1
    start %= N
    b.append(a[start])
    del a[start]
    N -= 1
print('<' + str(b).strip("]").strip("[") + '>')

