# -*- coding: utf-8 -*-
"""백준 10610 (30)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sxqIqkiHmPKC3ODQfKckqXdoZruP7lHS

**문제**

- 양수 N이 주어짐
- N에 섞인 숫자를 조합해서 30의 배수가 되는 가장 큰 수를 만들고 싶다..

**풀이**

- 수를 조합해서 30의 배수를 만들어야 한다
- 3의 배수 조건 : 다 더해서 3이 되어야 한다
- 10의 배수 조건 : 끝이 0이어야 한다

- 쓸데없는 조건문과 반복문이 없이 join()을 쓰니까 시간이 확 준다..
"""

#리스트로 만들고 내림차순 정렬..
N = list(input())
N.sort(reverse = True)

#정렬하면 어쨋든 0이 제일 끝이다..
if N[-1] == '0':
    #이제 3의 배수가 될 수 있는지 확인..
    sum = 0
    for i in N:
        sum += int(i)
    if sum % 3 == 0:
        print("".join(N))
        """
        for i in N:
            print(i, end='')
        """
    else:
        print(-1)
else:
    print(-1)