# -*- coding: utf-8 -*-
"""백준 1037 (약수)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17frtOaB19QuR3AUVq8595p_pNCh-RLdm

- 진짜 약수의 갯수가 주어진다.. (50이하의 갯수)
- 다음 줄에 해당하는 진짜 약수들이 주어진다..
- 그거 보고 찾아라..

**해결책**

- 진짜 약수의 갯수가 홀수이면 제곱수임에 유의했다..
- 사실 할 필요 없었다..
- 입력이 순서대로 들어오지 않을 수도 있으므로 소팅해주면 된다..
"""

num = int(input())
divider_list = list(map(int, input().split()))
divider_list.sort()

if (num %2 == 1):
    print(divider_list[num//2] ** 2)
else:
    print(divider_list[0] * divider_list[-1])