# -*- coding: utf-8 -*-
"""기초백제

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nTXNyx3QP5CiXXWPeCB6gt3lszdk-h90
"""

a = int(input())

print(a)

a = input()

print(a)

a = float(input())

print("%f" %a)

a, b = map(int, input().split())

print("%d %d" %(a, b))

a, b = map(str, input().split())

print("%s %s" %(b, a))

a = float(input())

print("%.2f" %a)

a = int(input())

print("%d %d %d" %(a, a, a))

a, b = map(int, input().split(':'))

print("%d:%d" %(a, b))

a, b, c = map(int, input().split('.'))

print("%04d.%02d.%02d" %(a, b, c))

a = input()

for i in range(len(a)) :
    if a[i]=='-' :
        print('',end='')
    else :
        print(a[i], end='')

a = input()

print(a)

a = input()

print(a)

#1023
a = float(input())

#1024
a = input()

for i in range(len(a)) :
    print("'%s'" %a[i])

#1025

a = input()

for i in range(5):
    print('[%s'+'0'*(4-i)+']' %a[i])

members={'name':'황예린', 'age':22}

print(members)

#6001번
print("Hello")

#6002
print("Hello World")

#6003
print("Hello")
print("World")

#6004
print("'Hello'")

#6005
print('"Hello World"')

#6006
print('"!@#$%^&*()' + "'")

#6007
print('"C:\Download\\\'hello\'' + '.py"')

#6008
print('print("Hello\\nWorld")')

#6009
a = input()
print(a)

#6010
a = int(input())
print("%d" %a)

#6011
a = float(input())
print(a)

#6012
a = int(input())
b = int(input())

print("%d" %b)
print("%d" %a)

#줄바꾸긴데 잘못나온듯

#6013
a = input()
b = input()

print(b)
print(a)

#6014
a = float(input())

print(a)
print(a)
print(a)

#6015
a, b = map(int, input().split())

print(a)
print(b)

#6016
a, b = map(str, input().split())

print(b, a)

#6017
a = input()

print(a, a, a)

#6018
a , b = map(int, input().split(':'))

print(a, b, sep=':')

#6019
year, month, date = map(int, input().split('.'))

print(date, month, year, sep='-')

#6020
a, b = map(str, input().split('-'))

print(a+b)

#6021
a = input()

for i in range(len(a)):
    print(a[i])

#6022
s = input()

print(s[0:2], s[2:4], s[4:6], sep = ' ')

#6023
hour, min, sec = map(str, input().split(':'))

print(min)

#6024
a, b = map(str, input().split())

print(a+b)

#6025
a, b = map(int, input().split())

print(a+b)

#6026
a = float(input())
b = float(input())

print(a+b)

#6027
a = int(input())

print('%x' %a)

#6028
a = int(input())

print('%X' %a)

#6029
a = input()
n = int(a, 16)

print('%o' %n)

#6030
n = ord(input())

print(n)

#6031
c = int(input())

print(chr(c))

#6032
a = int(input())

print(-a)

#6033
a = ord(input())

print(chr(a+1))

#6034
a, b = map(int, input().split())

print(a-b)

#6035
a, b = map(float, input().split())

print(a*b)

#6036
a, b = input().split()

print(a*int(b))

#6037
a = int(input())
b = input()

print(a*b)

#6038
a, b = map(int, input().split())

print(a ** b)

#6039
a, b = map(float, input().split())

print(a ** b)

#6040
a, b = map(int, input().split())

print(a // b)

#6041
a, b = map(int, input().split())

print(a % b)

#6042
a = float(input())

print("%.2f" %a)

#6043
a, b = map(float, input().split())

print(round((a/b), 3))

#round()의 중요성! %.3f를 사용하면 소수점 아래 3자리가 안넘어가도 3자리로 뜬다

#6044
a, b = map(int, input().split())

print(a+b)
print(a-b)
print(a*b)
print(a//b)
print(a%b)
print(round(a/b, 2))

#6045
a, b, c = map(int, input().split())

sum = a+b+c
avg = round(sum/3, 2)

print(sum, avg, end='')

#6046
a = int(input())

print(a<<1)

#정수를 2배로 곱하거나 나누어 계산해 주는 비트단위시프트연산자 <<, >>를 이용할 수 있다.
#컴퓨터 내부에는 2진수 형태로 값들이 저장되기 때문에,
#2진수 형태로 저장되어 있는 값들을 왼쪽(<<)이나 오른쪽(>>)으로
#지정한 비트 수만큼 밀어주면 2배씩 늘어나거나 1/2로 줄어드는데,

#예시
#n = 10
#print(n<<1)  #10을 2배 한 값인 20 이 출력된다.
#print(n>>1)  #10을 반으로 나눈 값인 5 가 출력된다.
#print(n<<2)  #10을 4배 한 값인 40 이 출력된다.
#print(n>>2)  #10을 반으로 나눈 후 다시 반으로 나눈 값인 2 가 출력된다.

#의미 : 2진법에서 뒤로 몇 칸을 미는지를 적는것!

#6047
a ,b = map(int, input().split())

print(a << b)

#6048
a, b = map(int, input().split())

if a < b :
    print("True")
else :
    print("False")

#6049
a, b = map(int, input().split())

if a == b :
    print("True")
else :
    print("False")

#6050
a, b = map(int, input().split())

if a <= b :
    print("True")
else :
    print("False")

#6051
a, b = map(int, input().split())

if a != b :
    print("True")
else :
    print("False")

#6052
a = int(input())

if a == 0 :
    print("False")
else :
    print("True")

# a = bool(int(input()))이라고 하면 a가 0일 때만 a에 False가 저장되고 나머지에는 True로 저장됨

#6053
a = bool(int(input()))

print(not a)

#6054
a, b = map(int, input().split())

print(bool(a) and bool(b))

#6055
a, b = map(int, input().split())

print(bool(a) or bool(b))

#6056
a, b = map(int, input().split())

if (bool(a) != bool(b)) :
    print("True")
else :
    print("False")

#6057
a, b = map(int, input().split())

if (bool(a) == bool(b)) :
    print("True")
else :
    print("False")

#6058
a, b = map(int, input().split())

if (not (bool(a) or bool(b)) ) :
    print("True")
else :
    print("False")

#6059
a = int(input())

print(~a)

#이러한 내용을 간단히 표현하면, 정수 n이라고 할 때,
#~n = -n - 1
#-n = ~n + 1 과 같은 관계로 표현할 수 있다.

#6060
a, b = map(int, input().split())

print( a&b )
#비트단위 연산자라는게 그냥 수를 2진수로 나타내서 연산하겟다는 것임

#6061
a, b = map(int, input().split())

print( a|b )

#6062
a, b = map(int, input().split())

print(a^b)
#그래픽 처리에서도 유용한데, 두장의 이미지가 겹쳐졌을 때 색이 서로 다른 부분만을 처리할수 있다

#6063
a, b = map(int, input().split())

print(max(a,b))

#6064
a, b, c = map(int, input().split())

print(min(a,b,c))

#6065
a, b, c = map(int, input().split())

if a % 2 == 0 :
    print(a)
if b % 2 == 0 :
    print(b)
if c % 2 == 0 :
    print(c)

#6066
a, b, c = map(int, input().split())

if a % 2 == 0 :
    print("even")
else :
    print("odd")
if b % 2 == 0 :
    print("even")
else :
    print("odd")
if c % 2 == 0 :
    print("even")
else :
    print("odd")

#6067
a = int(input())

if a < 0 :
    if a % 2 == 0 :
        print("A")
    else :
        print("B")
else : 
    if a % 2 == 0 :
        print("C")
    else : 
        print("D")

#6068
a = int(input())

if a >= 90 :
    print("A")
elif a >= 70 :
    print("B")
elif a >= 40 :
    print("C")
else :
    print("D")

#6069
grade = input()

if grade == 'A':
    print("best!!!")
elif grade == 'B':
    print("good!!")
elif grade == 'C':
    print("run!")
elif grade == 'D':
    print("slowly~")
else :
    print("what?")

#6070
month = int(input())

if month//3 == 1 :
    print("spring")
elif month//3 == 2 :
    print("summer")
elif month//3 == 3 :
    print("fall")
else :
    print("winter")

#6071
while True:
    a = int(input())
    if a == 0 :
        break
    else :
        print(a)

#6072
a = int(input())

for i in range(a, 0, -1):
    print(i)

#6073
a = int(input())

while a > 0 :
    print(a-1)
    a -= 1

#6074
a = ord(input())
t = ord('a')

while t<= a:
    print(chr(t), end = ' ')
    t += 1

#6075
a = int(input())

for i in range(a + 1):
    print(i)

#6076
a = int(input())

for i in range(a + 1):
    print(i)

#6077
a = int(input())
sum = 0

for i in range( a+1 ):
    if i % 2 == 0:
        sum += i

print(sum)

#6078
while True :
    a = input()
    print(a)
    
    if a == 'q':
        break

#6079
a = int(input())
sum = 0

for i in range(a+1):
    sum += i
    if sum >= a :
        break

print(i)

#6080
n, m = map(int, input().split())

for i in range(n):
    for j in range(m):
        print("%d %d" %(i+1, j+1))

#6081
a = input()
n = int(a, 16)          #a를 16진수의 정수로 바꾸는 방법 -> int(a,16)

for i in range(15):
    print('%X*%X=%X' %(n, i+1, n*(i+1)))

#6082
a = int(input())

for i in range(1,a+1):
    if (i%10 == 3) or (i%10 == 6) or (i%10 == 9):
        print('X', end = ' ')
    else :
        print(i, end = ' ')

#6083
a, b, c = map(int, input().split())
count = 0
for i in range(a):
    for j in range(b):
        for k in range(c):
            print(i, j, k)
            count = count + 1
print(count)

#6084
h, b, c, s = map(int, input().split())

storage = h*b*c*s/8/1024/1024
print("%.1f MB" %storage)

#6085
r, g, b = map(int, input().split())

storage = r*g*b/8/1024/1024
print("%.2f MB" %storage)

#6086
a = int(input())
sum = 0
i = 1

while True :
    sum = sum + i
    i = i + 1
    if sum >= a :
        break

print(sum)

#6087
a = int(input())
for i in range(1, a+1):
    if i%3 == 0:
        continue
    print(i, end = ' ')

#continue가 실행되면 반복문 내에서 continue아래의 행을 하지않고 다음 반복으로 넘어간다

#6088
a, d, n = map(int, input().split())

k = a + (n-1) * d
print(k)

#6089
a, r, n = map(int, input().split())

k = a*(r**(n-1))
print(k)

#6090
a, m, d, n = map(int, input().split())

k = a

for i in range(2, n+1):
    k = m*k + d

print(k)

