# -*- coding: utf-8 -*-
"""백준1004

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lCVV7MzZrx3Q6UwZdTGzAHqxXhvNGFvS
"""

T = int(input())

for t in range(T):
    count = 0
    x1, y1, x2, y2 = map(int, input().split())
    N = int(input())

    for n in range(N):
        Cx, Cy, Cr = map(int, input().split())
        
        d1 = ((x1-Cx) ** 2 + (y1-Cy) ** 2) ** 0.5
        d2 = ((x2-Cx) ** 2 + (y2-Cy) ** 2) ** 0.5

        if (d1-Cr)*(d2-Cr) < 0:
            count = count + 1
    
    print(count)